# This workflow will build a Java project with Maven

name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17 + GPG
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
    - name: Build with Maven (signed)
      run: mvn -B -ntp clean install -Dgpg.passphrase="${{ secrets.GPG_PASSPHRASE }}" -Dgpg.arguments="--pinentry-mode,loopback"
      
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: target
        path: target
